name: pati
channels:
  - anaconda
  - defaults
dependencies:
  - flask
  - jupyterlab
  - ipython=7.0.1 
  - matplotlib=3.0.0
  - notebook
  - numpy
  - pandas
  - python=3.6
  - scikit-learn=0.20.0
  - scipy=1.1.0
  - seaborn=0.9.0
  - pip:
      - flask
      - keras
      - pillow
      - tensorflow
